# This manually triggered workflow creates a new release.
name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  make_release:
    runs-on: ubuntu-24.04
    name: Create Release Source Archives
    env:
      XMLWRAPP_WITH_DOCS: 1
      XMLWRAPP_CMAKE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./scripts/ci/install.sh

      - name: Configure
        run: cmake -S . -B ../build-cmake

      - name: Create release archives
        run: cmake --build ../build-cmake --target dist

      - name: Check release archives
        run: cmake --build ../build-cmake --target distcheck

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: ../build-cmake/xmlwrapp-*.tar.*z
          fail_on_unmatched_files: true
          draft: true
